### ISSUE TITLE
How to decoding image using your package in flutter web?

### ISSUE THREAD

**Issue by bambinoua** [d-markey/squadron_sample#1]
I need to display create and show thumbnail before sending it to server. The thumbnail making process is enough long so I need to use isolates. Could you please to give me example how can I do this?

Suppose I have this code using `compute`:
```dart
Uint8List originFile = await FilePicker.pickFile(...);
Uint8List targetThumbnail = compute(createThumbnail, originFile);

Uint8List createThumbnail(Uint8List file) {
  return longProcedureWhichCropsAndCreatesThumbnail() as Uint8List;
}
```
What do I need to do to implement this using your package?

**Comment by d-markey** [comment]
Hello @bambinoua,

To implement this with Squadron is quite straightforward, the main thing is to implement a service that will be used by workers (web worker and/or isolates). Here's an example:

```dart
// this abstract class represents the functionality you want to support in your service
//
// in this example, there is only one functionality: given an image represented by imageData,
// compute a thumbnail of size (thumbWidth, thumbHeight)
abstract class ThumbnailService {
  FutureOr<Uint8List> getThumbnail(
      Uint8List imageData, int thumbWidth, int thumbHeight);

  // this constant is used to identify the method to call when communicating with isolates / web workers
  static const getThumbnailCommand = 1;
}

// this class is the actual implementation of the service defined above
class ThumbnailServiceImpl implements ThumbnailService, WorkerService {
  @override
  FutureOr<Uint8List> getThumbnail(
      Uint8List imageData, int thumbWidth, int thumbHeight) {
    // implementation using the image package (https://pub.dev/packages/image)
    var image = decodeImage(imageData)!;
    var thumbnail = copyResize(image, width: thumbWidth, height: thumbHeight);
    return Uint8List.fromList(encodePng(thumbnail));
  }

  // this map creates the correspondance between the service constants from ThumbnailService
  // and the method implementations in ThumbnailServiceImpl
  @override
  late final Map<int, CommandHandler> operations = {
    ThumbnailService.getThumbnailCommand: (WorkerRequest r) =>
        getThumbnail(r.args[0], r.args[1], r.args[2])
  };
}
```

The next thing is to wire everything up for Web workers/Isolates. Squadron provides everything necessary to bootstrap your service, fire up the workers and make your app communicate with the workers. So the rest of the code is rather automatic. You will find those components in the attached sample. Typically:

* a worker _per se_ (the Web worker / Isolate entry point) -- one for each platform
* a worker activator to instantiate the Web worker / Isolate -- one for each platform
* a worker pool to distribute work items to the workers

[thumbnail_sample.zip](https://github.com/d-markey/squadron_sample/files/7865743/thumbnail_sample.zip)

Hope this helps.

**Comment by d-markey** [comment]
PS: if you're using Squadron in a Web application, please note that you will need to compile the Web worker to JavaScript manually. Assuming your Web release folder is "/web", the command line to use is:

```
dart compile js ./lib/src/browser/thumbnail_worker.dart -o ./web/thumbnail_worker.dart.js -m
```

You will need to do this any time your Web worker or any dependency of the Web worker changes (typically the service you've implemented, or even a dependency of your service). Eg. this sample uses the [image](https://pub.dev/packages/image) package; if the package is updated, the Web worker must be recompiled. You can automate this in a script.

**Comment by bambinoua** [comment]
Hello, @d-markey!
Thank you for quick and expanded answer. Will try.

**Comment by d-markey** [comment]
OK, let me know if this is what you were looking for.

I've also updated the GitHub repo with the thumbnail sample to provide more examples of use cases and Squadron's possibilities.

**Comment by vinayak-ventura** [comment]
@d-markey any examples you have to work with web_socket_channel package, with all platforms, ios/android/web

**Comment by d-markey** [comment]
Nope, no example available with that specific package. You'll have to try it yourself and submit issues if you need further help.
